---
name: Build Targets

on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.gitignore'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    name: ${{ matrix.target }}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        target:
          - GZDoom
#          - Raze

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build target
        run: |
#          ./build.py --target ${{ matrix.target }}
          git clone https://github.com/alexey-lysiuk/gzdoom.git
          git -C gzdoom switch zmusic-system
          ./build.py --source=gzdoom

      - name: Generate Xcode project
        run: |
          ./build.py --target ${{ matrix.target }} --xcode

      - name: List Build Directory
        if: always()
        shell: bash
        run: |
          git status
          ls -lR .
...
